//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoShop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:1,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1055,&quot;Name&quot;:&quot;Doran&apos;s Blade&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:450,&quot;UpgradeCost&quot;:450,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3153,&quot;Name&quot;:&quot;Blade of the Ruined King&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:3400,&quot;UpgradeCost&quot;:750,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3144,&quot;Name&quot;:&quot;Bilgewater Cutlass&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1650,&quot;Upgra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericADC {
            get {
                return ResourceManager.GetString("GenericADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1413,&quot;Name&quot;:&quot;Enchantment: Cinderhulk&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:2625,&quot;UpgradeCost&quot;:525,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3715,&quot;Name&quot;:&quot;Skirmisher&apos;s Sabre&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1000,&quot;UpgradeCost&quot;:300,&quot;BuildFrom&quot;:[{&quot;Id&quot;:1041,&quot;Name&quot;:&quot;Hunter&apos;s Machete&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericJungleAD {
            get {
                return ResourceManager.GetString("GenericJungleAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1413,&quot;Name&quot;:&quot;Enchantment: Cinderhulk&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:2625,&quot;UpgradeCost&quot;:525,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3715,&quot;Name&quot;:&quot;Skirmisher&apos;s Sabre&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1000,&quot;UpgradeCost&quot;:300,&quot;BuildFrom&quot;:[{&quot;Id&quot;:1041,&quot;Name&quot;:&quot;Hunter&apos;s Machete&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericJungleADTank {
            get {
                return ResourceManager.GetString("GenericJungleADTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1414,&quot;Name&quot;:&quot;Enchantment: Runic Echoes&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:2625,&quot;UpgradeCost&quot;:340,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3715,&quot;Name&quot;:&quot;Skirmisher&apos;s Sabre&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1000,&quot;UpgradeCost&quot;:300,&quot;BuildFrom&quot;:[{&quot;Id&quot;:1039,&quot;Name&quot;:&quot;Hunter&apos;s Talisman&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericJungleAP {
            get {
                return ResourceManager.GetString("GenericJungleAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1401,&quot;Name&quot;:&quot;Enchantment: Cinderhulk&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:2625,&quot;UpgradeCost&quot;:525,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3706,&quot;Name&quot;:&quot;Stalker&apos;s Blade&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1000,&quot;UpgradeCost&quot;:300,&quot;BuildFrom&quot;:[{&quot;Id&quot;:1039,&quot;Name&quot;:&quot;Hunter&apos;s Talisman&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;Bui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericJungleAPTank {
            get {
                return ResourceManager.GetString("GenericJungleAPTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:1,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3142,&quot;Name&quot;:&quot;Youmuu&apos;s Ghostblade&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:3200,&quot;UpgradeCost&quot;:1000,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3134,&quot;Name&quot;:&quot;Serrated Dirk&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1100,&quot;UpgradeCost&quot;:400,&quot;BuildFrom&quot;:[{&quot;Id&quot;:1036,&quot;Name&quot;:&quot;Long Sword&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;BuildFrom&quot;:[],&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericMidAD {
            get {
                return ResourceManager.GetString("GenericMidAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:1,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1056,&quot;Name&quot;:&quot;Doran&apos;s Ring&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:400,&quot;UpgradeCost&quot;:400,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3285,&quot;Name&quot;:&quot;Luden&apos;s Echo&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:3200,&quot;UpgradeCost&quot;:1100,&quot;BuildFrom&quot;:[{&quot;Id&quot;:1058,&quot;Name&quot;:&quot;Needlessly Large Rod&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1250,&quot;UpgradeCost&quot;:12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericMidAP {
            get {
                return ResourceManager.GetString("GenericMidAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3097,&quot;Name&quot;:&quot;Targon&apos;s Brace&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:850,&quot;UpgradeCost&quot;:350,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3302,&quot;Name&quot;:&quot;Relic Shield&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1006,&quot;Name&quot;:&quot;Rejuvenation Bead&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:150,&quot;UpgradeCost&quot;:150,&quot;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericSupportADTank {
            get {
                return ResourceManager.GetString("GenericSupportADTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3092,&quot;Name&quot;:&quot;Frost Queen&apos;s Claim&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:2200,&quot;UpgradeCost&quot;:550,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3098,&quot;Name&quot;:&quot;Frostfang&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:850,&quot;UpgradeCost&quot;:375,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3303,&quot;Name&quot;:&quot;Spellthief&apos;s Edge&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;BuildFrom&quot;:[], [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericSupportAPBurst {
            get {
                return ResourceManager.GetString("GenericSupportAPBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3092,&quot;Name&quot;:&quot;Frost Queen&apos;s Claim&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:2200,&quot;UpgradeCost&quot;:550,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3098,&quot;Name&quot;:&quot;Frostfang&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:850,&quot;UpgradeCost&quot;:375,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3303,&quot;Name&quot;:&quot;Spellthief&apos;s Edge&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;BuildFrom&quot;:[], [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericSupportAPHeal {
            get {
                return ResourceManager.GetString("GenericSupportAPHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3069,&quot;Name&quot;:&quot;Talisman of Ascension&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:2200,&quot;UpgradeCost&quot;:800,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3096,&quot;Name&quot;:&quot;Nomad&apos;s Medallion&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:850,&quot;UpgradeCost&quot;:225,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3301,&quot;Name&quot;:&quot;Ancient Coin&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;BuildFrom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericSupportAPTank {
            get {
                return ResourceManager.GetString("GenericSupportAPTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3074,&quot;Name&quot;:&quot;Ravenous Hydra&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:3500,&quot;UpgradeCost&quot;:1050,&quot;BuildFrom&quot;:[{&quot;Id&quot;:1036,&quot;Name&quot;:&quot;Long Sword&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:350,&quot;UpgradeCost&quot;:350,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3077,&quot;Name&quot;:&quot;Tiamat&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1200,&quot;UpgradeCost&quot;:175,&quot;BuildFrom&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericTopAD {
            get {
                return ResourceManager.GetString("GenericTopAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:1,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1054,&quot;Name&quot;:&quot;Doran&apos;s Shield&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:450,&quot;UpgradeCost&quot;:450,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3068,&quot;Name&quot;:&quot;Sunfire Cape&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:2700,&quot;UpgradeCost&quot;:800,&quot;BuildFrom&quot;:[{&quot;Id&quot;:1031,&quot;Name&quot;:&quot;Chain Vest&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:800,&quot;UpgradeCost&quot;:500,&quot;BuildFr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericTopADTank {
            get {
                return ResourceManager.GetString("GenericTopADTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1056,&quot;Name&quot;:&quot;Doran&apos;s Ring&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:400,&quot;UpgradeCost&quot;:400,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3027,&quot;Name&quot;:&quot;Rod of Ages&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:3000,&quot;UpgradeCost&quot;:950,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3010,&quot;Name&quot;:&quot;Catalyst the Protector&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1200,&quot;UpgradeCost&quot;:45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericTopAP {
            get {
                return ResourceManager.GetString("GenericTopAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UseHPotion&quot;:true,&quot;MaxHPotionCount&quot;:3,&quot;MaxHPotionLevel&quot;:11,&quot;Items&quot;:[{&quot;Id&quot;:3340,&quot;Name&quot;:&quot;Warding Totem (Trinket)&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:0,&quot;UpgradeCost&quot;:0,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:1056,&quot;Name&quot;:&quot;Doran&apos;s Ring&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:400,&quot;UpgradeCost&quot;:400,&quot;BuildFrom&quot;:[],&quot;Sell&quot;:false},{&quot;Id&quot;:3027,&quot;Name&quot;:&quot;Rod of Ages&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:3000,&quot;UpgradeCost&quot;:950,&quot;BuildFrom&quot;:[{&quot;Id&quot;:3010,&quot;Name&quot;:&quot;Catalyst the Protector&quot;,&quot;BuyNowIfWeCan&quot;:false,&quot;TotalCost&quot;:1200,&quot;UpgradeCost&quot;:45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericTopAPTank {
            get {
                return ResourceManager.GetString("GenericTopAPTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;tree&quot;: [ { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;LANE&quot;, &quot;JUNGLE&quot; ], &quot;header&quot;: &quot;START&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;CONSUMABLE&quot;, &quot;GOLDPER&quot;, &quot;VISION&quot; ], &quot;header&quot;: &quot;TOOLS&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;HEALTH&quot;, &quot;ARMOR&quot;, &quot;SPELLBLOCK&quot;, &quot;HEALTHREGEN&quot; ], &quot;header&quot;: &quot;DEFENSE&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;DAMAGE&quot;, &quot;CRITICALSTRIKE&quot;, &quot;ATTACKSPEED&quot;, &quot;LIFESTEAL&quot; ], &quot;header&quot;: &quot;ATTACK&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;SPELLDAMAGE&quot;, &quot;COOLDOWNREDUCTION&quot;, &quot;MANA&quot;, &quot;MANAREGEN&quot; ], &quot;header&quot;: &quot;MAGIC&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;BOOTS&quot;, &quot;NO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
    }
}
